In [1]:
obs_dim = 10
lat_dim = 4
depth = 2
groups = None
ngroups = 2
reg = None


In [2]:
import tensorflow as tf
import tf as envae


2024-10-23 05:30:33.841443: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 05:30:33.844048: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-23 05:30:33.853436: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-23 05:30:33.868322: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-23 05:30:33.872628: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-23 05:30:33.883456: I tensorflow/core/platform/cpu_feature_gu

In [3]:
vae = envae.EnVAE(obs_dim, lat_dim, depth=depth, groups=groups, ngroups=ngroups, reg=reg)


In [4]:
inp = tf.random.uniform((6, obs_dim))
inp

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[0.700799  , 0.5734681 , 0.7612066 , 0.10107434, 0.74109983,
        0.08444536, 0.73024654, 0.14529622, 0.5347866 , 0.38430905],
       [0.60953856, 0.3737601 , 0.6014813 , 0.4596231 , 0.47612023,
        0.0911386 , 0.60392463, 0.8892423 , 0.3962735 , 0.74732053],
       [0.36215782, 0.6210047 , 0.04791236, 0.7305442 , 0.60434914,
        0.81510043, 0.23447919, 0.9700321 , 0.23224306, 0.91238165],
       [0.8597894 , 0.4512937 , 0.25677943, 0.46346605, 0.30752003,
        0.90639555, 0.913538  , 0.5601517 , 0.498608  , 0.97334015],
       [0.1503036 , 0.9035504 , 0.38365543, 0.88679194, 0.68429506,
        0.85647297, 0.72888374, 0.66638076, 0.7454294 , 0.92108023],
       [0.8690938 , 0.76375115, 0.7316867 , 0.79405653, 0.7043359 ,
        0.17089653, 0.98498905, 0.81844616, 0.7063812 , 0.6534678 ]],
      dtype=float32)>

In [5]:
enc = vae.encode(inp)
enc

(<tf.Tensor: shape=(6, 4, 3), dtype=float32, numpy=
 array([[[ 0.18845195,  0.01897655,  0.1331559 ],
         [-0.22974703, -0.00317947, -0.15400225],
         [-0.18718632, -0.01806543, -0.1397845 ],
         [-0.6457648 ,  0.02735074, -0.47103077]],
 
        [[ 0.13675801,  0.01631314,  0.09934293],
         [-0.17719416, -0.00471385, -0.11930677],
         [-0.12143949, -0.01219219, -0.08989077],
         [-0.45357132,  0.00745243, -0.31858638]],
 
        [[ 0.09984116,  0.07083896,  0.11613476],
         [-0.1090049 , -0.06114123, -0.11533549],
         [-0.11301678, -0.07729553, -0.12961161],
         [-0.3896735 ,  0.00431332, -0.26712897]],
 
        [[ 0.03216098,  0.09742511,  0.09859754],
         [-0.13013104,  0.013386  , -0.07167069],
         [-0.03155816, -0.04271423, -0.05241507],
         [-0.5848909 , -0.01931216, -0.39202797]],
 
        [[ 0.21361822,  0.14441568,  0.24042305],
         [-0.2860439 ,  0.08322617, -0.14033413],
         [-0.34461412, -0.063213  , 

In [6]:
samp = vae.reparameterize(*enc)
samp

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[-0.36145276, -1.0444593 , -0.05346659, -0.504808  ],
       [ 0.42126393, -0.3077658 ,  0.4717597 , -0.6657489 ],
       [ 0.648548  ,  0.11169863,  0.5613223 ,  0.78558195],
       [ 0.11356014, -0.42135522,  0.3088906 ,  0.17152381],
       [ 0.74573654, -0.58220565, -0.59966505,  0.01687767],
       [-0.18951212,  0.2080687 ,  0.36271957, -0.8500937 ]],
      dtype=float32)>

In [10]:
dec_stoch = vae.decode(tf.math.reduce_mean(enc[0], axis=-1))
dec_stoch

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[-2.22806379e-01,  1.44904673e-01,  1.90926015e-01,
        -2.29245275e-01, -3.88919264e-02, -1.16185978e-01,
        -6.78046122e-02,  9.93546173e-02,  6.31514564e-03,
         1.34718657e-01],
       [-1.56944081e-01,  1.01109490e-01,  1.47025451e-01,
        -1.60445720e-01, -2.88391281e-02, -8.59915316e-02,
        -5.49692735e-02,  7.29736090e-02,  4.77455184e-03,
         1.00511223e-01],
       [-1.01351924e-01,  1.03314281e-01,  1.37260884e-01,
        -1.75059855e-01, -3.01536582e-02, -9.17483121e-02,
        -6.33227974e-02,  8.55289698e-02, -1.45943835e-04,
         1.07814141e-01],
       [-2.42315024e-01,  1.04013860e-01,  1.34526342e-01,
        -1.47852898e-01, -1.49710663e-02, -5.83198257e-02,
        -2.17717588e-02,  4.20109704e-02,  1.72635149e-02,
         6.35593235e-02],
       [-1.69895619e-01,  2.02060357e-01,  2.20667303e-01,
        -3.45335722e-01, -4.00120020e-02, -1.47917956e-01,
        -9.57652479e-

In [8]:
dec_determ = vae.decode(samp)
dec_determ

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[-0.7927299 ,  0.22489363,  0.46030173, -0.32813716, -0.33939743,
        -0.46270087, -0.23717552,  0.32163152, -0.12864989,  0.5827205 ],
       [-0.54963934,  0.07470646,  0.82999086, -0.0831071 ,  0.01749224,
        -0.10805982, -0.29232   ,  0.05689639,  0.12559082,  0.13324401],
       [-0.07884943, -0.22278121,  0.27278775,  0.61685514,  0.38772258,
         0.0975661 , -0.25113252, -0.2601669 ,  0.4801189 , -0.00770335],
       [-0.09504434, -0.08453196,  0.34120697,  0.15786757,  0.17648551,
        -0.05697453, -0.22377348,  0.01962627,  0.2503955 ,  0.11704499],
       [-0.06000305,  0.29303548,  0.20243022, -0.6927813 ,  0.2979789 ,
        -0.53638715, -0.1901496 ,  0.5787212 ,  0.36865285,  0.6807159 ],
       [-1.0323254 ,  0.0178062 , -0.07784313, -0.01518962,  0.08423187,
        -0.0176148 ,  0.31986877,  0.00465269,  0.10412782,  0.02099818]],
      dtype=float32)>

In [13]:
hvae = envae.EnVAE(obs_dim, lat_dim, depth=depth, groups={0: vae.groups[0]}, ngroups=None, reg=reg)
hvae.encode(inp)
hvae.decode(tf.math.reduce_mean(enc[0], axis=-1)), hvae.decode(samp)


(<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
 array([[ 0.19624455,  0.        , -0.1593048 ,  0.        , -0.18655504,
          0.        ,  0.17923844,  0.        ,  0.16123573,  0.        ],
        [ 0.1410809 ,  0.        , -0.10962109,  0.        , -0.13246985,
          0.        ,  0.12555212,  0.        ,  0.10827514,  0.        ],
        [ 0.14524128,  0.        , -0.1077349 ,  0.        , -0.13465887,
          0.        ,  0.12580661,  0.        ,  0.10349523,  0.        ],
        [ 0.12560038,  0.        , -0.1211284 ,  0.        , -0.1258307 ,
          0.        ,  0.12762877,  0.        ,  0.13305274,  0.        ],
        [ 0.26069945,  0.        , -0.21116816,  0.        , -0.24767353,
          0.        ,  0.23779865,  0.        ,  0.21347739,  0.        ],
        [ 0.2169701 ,  0.        , -0.19189595,  0.        , -0.21154723,
          0.        ,  0.20878819,  0.        ,  0.20282176,  0.        ]],
       dtype=float32)>,
 <tf.Tensor: shape=(6, 10), dty